# Generated by Django 4.1 on 2023-07-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scrap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scrap_id", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "scrap",
                "managed": False,
            },
        ),
    ]
